- name: Configurar hostname, Syslog, NTP e Timezone nos switches
  shell: |
    set -o pipefail
    {
      sleep 1
      printf "\r";                      sleep 1
      printf "terminal length 0\r";     sleep 1
      printf "conf t\r";                 sleep 1

      # Hostname
      printf "hostname {{ inventory_hostname }}\r"; sleep 1

      # Syslog
      printf "logging host 10.25.108.13\r"; sleep 1

      # NTP
      printf "ntp server 10.25.108.25\r"; sleep 1

      # Timezone
      printf "clock timezone BRT -3\r"; sleep 1

      printf "end\r";                    sleep 1
      printf "wr mem\r";                 sleep 1
      printf "exit\r"
    } | telnet {{ hostvars[inventory_hostname].ansible_host }} 23
  args:
    executable: /bin/bash
  register: telnet_out
  failed_when: false
  changed_when: "'% Invalid input' not in (telnet_out.stdout | default(''))"

- name: Diagnóstico (stdout)
  debug:
    var: telnet_out.stdout_lines

